[package]
name = "pom-eth-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web3 = "0.18.0"
ethabi = "17.2.0"
hex = "0.4"
thiserror = "1.0"
dotenv = "0.15.0"
anyhow = "1.0"

[[bin]]
name = "eth-integration"
path = "src/main.rs"